# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Makamakaole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FenceCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fence_check_date', models.DateField(default=datetime.date.today)),
                ('enclosure', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('culverts_sound', models.BooleanField(default=True)),
                ('fenceline_sound', models.BooleanField(default=True)),
                ('hood_sound', models.BooleanField(default=True)),
                ('gate_sound', models.BooleanField(default=True)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makamakaole_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SoundCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_check_date', models.DateField(default=datetime.date.today)),
                ('enclosure', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('battery', models.IntegerField()),
                ('battery2', models.IntegerField()),
                ('ants', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='burrowmonitoring',
            name='burrow_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='burrowmonitoring',
            name='scent_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='burrowmonitoring',
            name='ant_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='burrowmonitoring',
            name='burrow_num',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='burrowmonitoring',
            name='chick_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='burrowmonitoring',
            name='feather_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='burrowmonitoring',
            name='monitoring_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='burrowmonitoring',
            name='nest_material_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='burrowmonitoring',
            name='notes',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='burrowmonitoring',
            name='other_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='burrowmonitoring',
            name='tootpick_activity',
            field=models.BooleanField(default=False),
        ),
    ]
