# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0001_initial'),
        ('Makamakaole', '0003_generalnotes_note_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outplanting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outplanting_date', models.DateField(default=datetime.date.today)),
                ('enclosure', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('number', models.PositiveIntegerField()),
                ('notes', models.TextField()),
                ('plant_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.PlantSpecies')),
            ],
        ),
        migrations.AlterField(
            model_name='burrowmonitoring',
            name='notes',
            field=models.TextField(),
        ),
    ]
