# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0006_auto_20170215_0857'),
        ('Makamakaole', '0005_nightsurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='BANOControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('loc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('BANO_observerd', models.PositiveIntegerField()),
                ('BANO_controlled', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('staff1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obs1', to='lookup_tables.Personnel')),
                ('staff2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obs2', to='lookup_tables.Personnel')),
            ],
        ),
        migrations.AddField(
            model_name='nightsurvey',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='burrowmonitoring',
            name='monitoring_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='burrowmonitoring',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fencecheck',
            name='fence_check_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fencecheck',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalnotes',
            name='makamakaole_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalnotes',
            name='note_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nightsurvey',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nightsurvey',
            name='survey_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='outplanting',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outplanting',
            name='outplanting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='soundcheck',
            name='sound_check_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
