# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Makamakaole', '0007_auto_20170217_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightsurvey',
            name='location_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='lookup_tables.Site'),
        ),
        migrations.AlterField(
            model_name='nightsurvey',
            name='wind_dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dir', to='lookup_tables.Direction'),
        ),
        migrations.AlterField(
            model_name='nightsurveyobservations',
            name='flight_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction', to='lookup_tables.Direction'),
        ),
        migrations.AlterField(
            model_name='nightsurveyobservations',
            name='parent_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_survey', to='Makamakaole.NightSurvey'),
        ),
        migrations.AlterField(
            model_name='nightsurveyobservations',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_def', to='lookup_tables.SpeciesDef'),
        ),
        migrations.AlterField(
            model_name='outplanting',
            name='plant_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='lookup_tables.PlantSpecies'),
        ),
    ]
