# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bait_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_text', models.CharField(max_length=50)),
                ('direction_short', models.CharField(max_length=2)),
                ('direction_deg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NightSurvey_Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NightSurvey_Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_range', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NightSurvey_Elevation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('initials', models.CharField(max_length=20)),
                ('staff_type', models.CharField(max_length=50)),
                ('hire_date', models.DateField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('hawaiian_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('distribution', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SizeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_txt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('species_code', models.CharField(max_length=10)),
                ('size_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.SizeClass')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_txt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrapType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trap_type_text', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('check_frequency', models.IntegerField()),
                ('target_species', models.ManyToManyField(to='lookup_tables.SpeciesDef')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='speciesdef',
            name='species_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Status'),
        ),
        migrations.AddField(
            model_name='bait',
            name='target_species',
            field=models.ManyToManyField(to='lookup_tables.SpeciesDef'),
        ),
    ]
