# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Canine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own', to='lookup_tables.Site')),
                ('physical_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='lookup_tables.Site')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='affiliation',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
