# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0002_auto_20170207_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_text', models.CharField(max_length=50)),
            ],
        ),
    ]
