# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0003_bandcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='short',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
