# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0005_auto_20170209_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomPoints',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('to_10', models.DecimalField(decimal_places=10, max_digits=20)),
                ('to_20', models.DecimalField(decimal_places=10, max_digits=20)),
                ('to_30', models.DecimalField(decimal_places=10, max_digits=20)),
                ('to_40', models.DecimalField(decimal_places=10, max_digits=20)),
                ('to_50', models.DecimalField(decimal_places=10, max_digits=20)),
                ('to_60', models.DecimalField(decimal_places=10, max_digits=20)),
                ('to_70', models.DecimalField(decimal_places=10, max_digits=20)),
                ('to_80', models.DecimalField(decimal_places=10, max_digits=20)),
                ('total_searchable', models.DecimalField(decimal_places=10, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='site',
            name='geom',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='site',
            name='loc',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='lookup_tables.Site'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='physical_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographic_location', to='lookup_tables.Site'),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='searcharea',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Site'),
        ),
        migrations.AddField(
            model_name='searcharea',
            name='turbine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Infrastructure'),
        ),
        migrations.AddField(
            model_name='randompoints',
            name='near',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Infrastructure'),
        ),
        migrations.AddField(
            model_name='randompoints',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Site'),
        ),
    ]
