# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0008_auto_20170220_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
