# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0009_infrastructure_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='turbine',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
