# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0010_infrastructure_turbine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
