# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0013_auto_20170220_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='turbine',
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
