# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0014_auto_20170220_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searcharea',
            old_name='to_10',
            new_name='from_0_to_10',
        ),
        migrations.RenameField(
            model_name='searcharea',
            old_name='to_20',
            new_name='from_10_to_20',
        ),
        migrations.RenameField(
            model_name='searcharea',
            old_name='to_30',
            new_name='from_20_to_30',
        ),
        migrations.RenameField(
            model_name='searcharea',
            old_name='to_40',
            new_name='from_30_to_40',
        ),
        migrations.RenameField(
            model_name='searcharea',
            old_name='to_50',
            new_name='from_40_to_50',
        ),
        migrations.RenameField(
            model_name='searcharea',
            old_name='to_60',
            new_name='from_50_to_60',
        ),
        migrations.RenameField(
            model_name='searcharea',
            old_name='to_70',
            new_name='from_60_to_70',
        ),
        migrations.RenameField(
            model_name='searcharea',
            old_name='to_80',
            new_name='from_70_to_80',
        ),
    ]
