# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0015_auto_20170220_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searcharea',
            name='total_searchable',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
