"""
This script takes the predictive shapes generated by the 
predictive shapes script and compares them to the fatalities.
"""
import sys
import arcpy

#Set environment variables, workspace to current directory and overwrite existing files.
arcpy.env.workspace = sys.path[0]
arcpy.env.overwriteOutput = True

#Get parameters from the ArcGIS toolbox window.
pointFeatureClass = arcpy.GetParameterAsText(0)
polygonFeatureClass = arcpy.GetParameterAsText(1)
output = arcpy.GetParameterAsText(2)

#Set spatial reference to EPSG:32604 WGS 84: UTM Zone 4N Hawaii
prj = arcpy.SpatialReference(32604)

#create temp working files for shapefile merging
pointtemp = "pointtemp.shp"
polytemp = "polytemp.shp"

#Search cursor to match the predictive shape with the appropriate fatality
pointcursor=arcpy.da.SearchCursor(pointFeatureClass,
                                  ["Shape@", "SiteTurb"],
                                  "",
                                  prj)


collector=[]

#Check if the output exists and delete if it already exists.
if arcpy.Exists("test.shp"):
    arcpy.Delete_management("test.shp")

#Iterate over each fatality in the input shapefile
for point in pointcursor:
    
    #Select the shape which has the same name and turbine as the fatality
    polycursor = arcpy.da.SearchCursor(polygonFeatureClass,
                                       ["shape@", "SitTurb"],
                                       "",
                                       prj)
    
    for poly in polycursor:
        #test if the point intersects the polygon for each turbine/date
        if point[1].rstrip() == poly[1].rstrip():
            arcpy.Select_analysis(pointFeatureClass, 
                                  pointtemp,
                                  '"SiteTurb" = '+"'"+str(point[1])+"'")
            arcpy.Select_analysis(polygonFeatureClass, 
                                  polytemp,
                                  '"SitTurb" = '+ "'" +str(poly[1])+"'")
            #test intersection
            arcpy.SpatialJoin_analysis(pointtemp,
                                       polytemp,
                                       "test.shp")
            testcurs = arcpy.da.SearchCursor("test.shp", 
                                             ['SitTurb'])
            for line in testcurs:
                #if the site and turbine are not in the polygon skip
                if line[0] != poly[1]:
                    del testcurs
                #if the site and turbine are in the polygon,
                #append the point to the overlap shapefile.
                else:
                    collector.append(arcpy.CreateUniqueName("overlap.shp"))
                    arcpy.CopyFeatures_management("test.shp", 
                                                  arcpy.CreateUniqueName("overlap.shp"))
                    del testcurs

    del poly    
#Destroy variables to save changes
del point
del pointcursor
del polycursor
arcpy.Merge_management(collector, output)
arcpy.Delete_management("test.shp")
for item in collector:
    arcpy.Delete_management(item)
