# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 21:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup_tables', '0002_auto_20170207_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownedWildlifeMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery_date', models.DateField(default=datetime.date.today)),
                ('search_type', models.CharField(choices=[('Visual', 'visual'), ('Canine', 'canine')], max_length=20)),
                ('search_incidental', models.CharField(choices=[('Search', 'search'), ('Incidental', 'incidental')], max_length=20)),
                ('affiliation', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Unknown', 'unknown')], max_length=50)),
                ('time_discovered', models.TimeField()),
                ('location_description', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bearing', models.PositiveIntegerField()),
                ('ground_cover', models.CharField(max_length=200)),
                ('wind_speed', models.PositiveIntegerField()),
                ('cloud_cover', models.PositiveIntegerField()),
                ('cloud_deck', models.CharField(max_length=50)),
                ('temp', models.PositiveIntegerField()),
                ('animal_condition', models.CharField(choices=[('Alive', 'alive'), ('Dead', 'dead')], max_length=20)),
                ('description', models.TextField()),
                ('photo_structure', models.ImageField(upload_to='')),
                ('photo_as_found', models.ImageField(upload_to='')),
                ('photo_as_found2', models.ImageField(upload_to='')),
                ('photo_injury', models.ImageField(upload_to='')),
                ('photo_other', models.ImageField(upload_to='')),
                ('notes', models.TextField()),
                ('report_date', models.DateField()),
                ('time_reported', models.DateTimeField()),
                ('time_responded', models.DateTimeField()),
                ('time_collected', models.DateTimeField()),
                ('date_last_searched', models.DateField()),
                ('weather_TOD', models.CharField(max_length=200)),
                ('outside', models.BooleanField()),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Age')),
                ('canine_searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Canine')),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected', to='lookup_tables.Personnel')),
                ('discovered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discover', to='lookup_tables.Personnel')),
                ('precip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Weather')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Site')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.SpeciesDef')),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Infrastructure')),
                ('wind_dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Direction')),
            ],
        ),
    ]
