# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0003_bandcolor'),
        ('downed_wildlife_monitoring', '0002_auto_20170208_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='WEOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_date', models.DateField(default=datetime.date.today)),
                ('obs_time', models.TimeField(default=datetime.datetime(2017, 2, 8, 9, 34, 39, 575809))),
                ('number', models.PositiveIntegerField()),
                ('banded', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('None', 'None'), ('Unknown', 'Unknown')], max_length=20)),
                ('color_band_leg', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('None', 'None'), ('Unknown', 'Unknown')], max_length=20)),
                ('color_band_id', models.CharField(max_length=5)),
                ('usgs_band', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left'), ('None', 'None'), ('Unknown', 'Unknown')], max_length=20)),
                ('behavior', models.CharField(choices=[('Standing', 'Standing'), ('Feeding', 'Feeding'), ('Flying', 'Flying'), ('Sitting', 'Roosting'), ('Foraging', 'Foraging'), ('Roosting', 'Roosting'), ('Other', 'Other')], max_length=20)),
                ('flight_altitude', models.PositiveIntegerField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cloud_cover', models.PositiveIntegerField()),
                ('flight_dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='lookup_tables.Direction')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Personnel')),
                ('precip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Weather')),
                ('primary_band_color', models.ForeignKey(default='Yellow', on_delete=django.db.models.deletion.CASCADE, related_name='Primary', to='lookup_tables.BandColor')),
                ('secondary_band_color', models.ForeignKey(default='Black', on_delete=django.db.models.deletion.CASCADE, related_name='Secondary', to='lookup_tables.BandColor')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Site')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.SpeciesDef')),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Infrastructure')),
                ('wind_dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wind', to='lookup_tables.Direction')),
            ],
        ),
        migrations.AlterField(
            model_name='caremonitoring',
            name='condition',
            field=models.CharField(choices=[('Intact', 'Intact'), ('Scavenged', 'Scavenged'), ('Odor', 'Odor'), ('Moved', 'Moved'), ('Feather/Hair loss', 'Feather/Hair loss'), ('Feather/Hair pile', 'feather/hair pile'), ('Ants', 'Ants'), ('Beetles', 'Beetles'), ('Flies', 'Flies'), ('Larvae', 'Larvae'), ('Skeleton visible', 'Skeleton visible'), ('Skeleton only', 'Skeleton only'), ('Dessicated', 'Dessicated'), ('Gone', 'Gone'), ('Other (notes)', 'Other (notes)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='animal_condition',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead')], max_length=20),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='search_incidental',
            field=models.CharField(choices=[('Search', 'Search'), ('Incidental', 'Incidental')], max_length=20),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='search_type',
            field=models.CharField(choices=[('Visual', 'Visual'), ('Canine', 'Canine')], max_length=20),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kwpiisearching',
            name='search_type',
            field=models.CharField(choices=[('Visual', 'Visual'), ('Canine', 'Canine')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kwpisearching',
            name='search_type',
            field=models.CharField(choices=[('Visual', 'Visual'), ('Canine', 'Canine')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wacardswap',
            name='detector_type',
            field=models.CharField(choices=[('Ground', 'Ground'), ('Nacelle', 'Nacelle')], max_length=50),
        ),
    ]
