# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('downed_wildlife_monitoring', '0003_auto_20170208_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caremonitoring',
            name='monitor_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 18, 42, 35, 174617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caresetup',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 18, 42, 35, 173617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='discovery_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 18, 42, 35, 170617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 18, 42, 35, 170617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kwpiisearching',
            name='monitor_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 18, 42, 35, 176617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kwpisearching',
            name='monitor_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 18, 42, 35, 175617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nenesurvey',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 18, 42, 35, 172617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wacardswap',
            name='swap_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 18, 42, 35, 178617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weop',
            name='obs_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 18, 42, 35, 179618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weop',
            name='obs_time',
            field=models.TimeField(default=datetime.datetime(2017, 2, 9, 18, 42, 35, 179618, tzinfo=utc)),
        ),
    ]
