# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('downed_wildlife_monitoring', '0004_auto_20170209_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caremonitoring',
            name='monitor_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='caresetup',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='discovery_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 18, 48, 37, 457842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='report_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kwpiisearching',
            name='monitor_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='kwpisearching',
            name='monitor_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='nenesurvey',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='wacardswap',
            name='swap_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='weop',
            name='obs_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='weop',
            name='obs_time',
            field=models.TimeField(default=datetime.datetime(2017, 2, 9, 8, 48, 37, 466843)),
        ),
    ]
