# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 21:02
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downed_wildlife_monitoring', '0014_auto_20170209_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='caremonitoring',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='caresetup',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='downedwildlifemonitoring',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='seefmaster',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='weop',
            name='obs_time',
            field=models.TimeField(default=datetime.datetime(2017, 2, 14, 11, 2, 3, 423000)),
        ),
    ]
