# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downed_wildlife_monitoring', '0020_auto_20170220_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seefmaster',
            name='point_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.RandomPoints'),
        ),
    ]
