# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downed_wildlife_monitoring', '0021_auto_20170221_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caremonitoring',
            name='parent',
            field=models.ForeignKey(help_text=b'Related to CARE Setup ID', on_delete=django.db.models.deletion.CASCADE, to='downed_wildlife_monitoring.CareSetUp'),
        ),
        migrations.AlterField(
            model_name='caremonitoring',
            name='present',
            field=models.BooleanField(help_text=b'True if present'),
        ),
        migrations.AlterField(
            model_name='caresetup',
            name='carcass_number',
            field=models.PositiveIntegerField(help_text=b'sequential number for each carcass in trial'),
        ),
        migrations.AlterField(
            model_name='caresetup',
            name='direction',
            field=models.PositiveIntegerField(help_text=b'bearing from the turbine to the CARE location'),
        ),
        migrations.AlterField(
            model_name='caresetup',
            name='distance',
            field=models.PositiveIntegerField(help_text=b'distance in meters from the turbine'),
        ),
        migrations.AlterField(
            model_name='caresetup',
            name='trial',
            field=models.CharField(help_text=b'trial ID, unique for each CARE trial', max_length=3),
        ),
        migrations.AlterField(
            model_name='caresetup',
            name='vegetation',
            field=models.CharField(help_text=b'relative vegetation height', max_length=50),
        ),
        migrations.AlterField(
            model_name='caresetup',
            name='waypoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CARE_waypoint', to='lookup_tables.RandomPoints'),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='cloud_cover',
            field=models.PositiveIntegerField(help_text=b'Percent'),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='date_last_searched',
            field=models.DateField(help_text=b'The date of the last monitoring'),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='description',
            field=models.TextField(help_text=b'describe the carcass: injuries, fat, condition, etc...'),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='photo_as_found',
            field=models.ImageField(blank=True, help_text=b'Photo of the carcass from just above', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='photo_as_found2',
            field=models.ImageField(blank=True, help_text=b'Photo of the carcass opposite side', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='photo_injury',
            field=models.ImageField(blank=True, help_text=b'Close up of animal injury', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='photo_other',
            field=models.ImageField(blank=True, help_text=b'Additional photo if needed', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='photo_structure',
            field=models.ImageField(blank=True, help_text=b'Photo relative to the structure', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='temp',
            field=models.PositiveIntegerField(help_text=b'degrees fahrenheit'),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='time_collected',
            field=models.DateTimeField(blank=True, help_text=b'What time was the specimen collected', null=True),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='time_reported',
            field=models.DateTimeField(blank=True, help_text=b'What time were the agencies first notified', null=True),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='time_responded',
            field=models.DateTimeField(blank=True, help_text=b'What time did the agencies respond', null=True),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='wind_speed',
            field=models.PositiveIntegerField(help_text=b'Meters per second'),
        ),
        migrations.AlterField(
            model_name='kwpiisearching',
            name='temp',
            field=models.PositiveIntegerField(help_text=b'degrees fahrenheit'),
        ),
        migrations.AlterField(
            model_name='kwpiisearching',
            name='wind_dir',
            field=models.ForeignKey(help_text=b'direction wind is blowing from(NE for trades)', on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Direction'),
        ),
        migrations.AlterField(
            model_name='kwpiisearching',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, help_text=b'meters per second', max_digits=5),
        ),
        migrations.AlterField(
            model_name='kwpisearching',
            name='cloud_cover',
            field=models.PositiveIntegerField(help_text=b'percent'),
        ),
        migrations.AlterField(
            model_name='kwpisearching',
            name='temp',
            field=models.PositiveIntegerField(help_text=b'degrees fahrenheit'),
        ),
        migrations.AlterField(
            model_name='kwpisearching',
            name='wind_dir',
            field=models.ForeignKey(help_text=b'direction wind is blowing from(NE for trades)', on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Direction'),
        ),
        migrations.AlterField(
            model_name='kwpisearching',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, help_text=b'meters per second', max_digits=5),
        ),
        migrations.AlterField(
            model_name='nenesurvey',
            name='count',
            field=models.PositiveIntegerField(help_text=b'Total number of Nene observed'),
        ),
        migrations.AlterField(
            model_name='seefmaster',
            name='canine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Canine'),
        ),
        migrations.AlterField(
            model_name='seefmaster',
            name='found',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seefmaster',
            name='not_recovered',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seefmaster',
            name='searcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searcher', to='lookup_tables.Personnel'),
        ),
    ]
