# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('downed_wildlife_monitoring', '0022_auto_20170310_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='canine_searcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Canine'),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='date_last_searched',
            field=models.DateField(blank=True, help_text=b'The date of the last monitoring', null=True),
        ),
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='report_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
