# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downed_wildlife_monitoring', '0023_auto_20170310_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='downedwildlifemonitoring',
            name='IDKey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
