# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downed_wildlife_monitoring', '0024_downedwildlifemonitoring_idkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downedwildlifemonitoring',
            name='IDKey',
            field=models.CharField(blank=True, help_text=b'YYYYMMDD_Site_Turbine_speciesCode i.e. 20170322_KWPI_T01_COMY', max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='caresetup',
            unique_together=set([('trial', 'carcass_number')]),
        ),
    ]
